# Generated by Django 4.1.7 on 2023-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choises_choise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
